//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vizeproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademik
    {
        public string id { get; set; }
        public string Ogretmenad { get; set; }
        public string Bolumders { get; set; }
        public string Baslangic { get; set; }
        public string Ayrilis { get; set; }
    }
}
