//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vizeproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversiteEntities : DbContext
    {
        public UniversiteEntities()
            : base("name=UniversiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginTb> LoginTb { get; set; }
        public virtual DbSet<Akademik> Akademik { get; set; }
        public virtual DbSet<BolumTb> BolumTb { get; set; }
        public virtual DbSet<Idari> Idari { get; set; }
        public virtual DbSet<Raporlar> Raporlar { get; set; }
        public virtual DbSet<Giris_Tb> Giris_Tb { get; set; }
    }
}
